### PR TITLE
Add version macros

### PR DESCRIPTION
**Pull request by averne**
This is to implement a shader cache, I want to invalidate everything when the deko3d version changes.
I went for the most straightforward way, you could also imagine a function or something and pass the version in the makefile as defines.

### CODE REVIEW

**Comment by fincs** [comment]
Hmm, what do you mean by shader cache, is this about a captured command cache? deko3d/uam do not support runtime shader compilation...

**Comment by averne** [comment]
I'm using my own fork of uam rigged for runtime compilation, not the prettiest thing but it works. https://github.com/averne/libuam
I'm working on porting mpv, which generates shaders at runtime for various things (yuv -> rgb conversion, hdr peak computation, all kinds of filters...).

**Comment by fincs** [comment]
Heh, so it turns out to be exactly what I feared it would be. If I am honest with you, the UAM codebase was never really intended as anything other than a temporary solution to provide a working/usable shader compiler tool for deko3d. I had hoped people would step in and offer help in writing a more appropriate shader compiler that would support more Maxwell features, and perhaps be more mindful of resources so that certain niche dynamic shader generation use cases like yours could even be covered. Unfortunately it doesn't seem like that idea has come to fruition.

Setting a precedent for a port of UAM that runs directly on device isn't something I'm exactly happy with, as that contravenes one of the main design goals of deko3d, which was nudging people to exclusively use precompiled shaders, not to mention eliminating the code size and memory usage overhead caused by mesa.

With that said, the shader ABI used by deko3d isn't something I expect to change in the future, at least not in backwards incompatible ways.

**Comment by averne** [comment]
I see. Honestly I don't think I'm personally knowledgeable enough about the maxwell ISA to start or even help build a shader compiler. The only people up for it would probably be you and a handful of emu developers.
My other option here would be to generate precompiled shaders for everything mpv can generate then use its shadercache functionality, but I decided against it considering the amount of variations it can make, and it also wouldn't support user-shaders well enough.

**Pull request closed without merging**
